version: '3.8'

services:
  backend:
    image: final-project/backend:latest
    build: ./back
    deploy:
      replicas: 2
    ports:
      - "3000:3000"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/tasks
    networks:
      - app-network

  frontend:
    image: final-project/frontend:latest
    build: ./front
    deploy:
      replicas: 2
    ports:
      - "80:80"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  mongo-data: