version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/tasks
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    build: ./front
    ports:
      - "80:80"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
